# Generated by Django 5.2.6 on 2025-11-04 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_ciudad_codigopostal_estado_pais_direccion_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.estado'),
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.pais'),
        ),
    ]
