# Generated by Django 5.2.7 on 2025-11-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_ciudad_estado_estado_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='codigopostal',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
